/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_cameraview_demo_OpenCVStitchImages */

#ifndef _Included_com_google_android_cameraview_demo_OpenCVStitchImages
#define _Included_com_google_android_cameraview_demo_OpenCVStitchImages
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_cameraview_demo_OpenCVStitchImages
 * Method:    stichImages
 * Signature: ([JJ)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_cameraview_demo_OpenCVStitchImages_stichImages
  (JNIEnv *, jclass, jlongArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
